### ISSUE TITLE
We should create some Labels and Milestones

### ISSUE THREAD

**Issue by DanielRuf** [ACCORD5/TrellisDesk#22]
So we can make some plans for future updates and also categorize the issues (feature request, bug fix, feature addition, ...)

**Comment by djtarazona** [comment]
Definitely will be looking into this over the weekend.  In all honestly (no secrets here), I'm a bit new to managing an open source project and am looking into how we can better collaborate, set goals / priorities, etc.  Of course, I'm open to suggestions!

At my local job, we have just begun using Redmine which is really nice.  However, it is a bit overkill just for this project, especially since Github has collaboration and project management tools built in and I'd really prefer not using two separate platforms.

**Comment by DanielRuf** [comment]
Well, its not so hard to work with git and Github ... You can also create an organization and create teams with perms for pull, push, ...

If you need help just write me =)

Its not my first project here.

If you dont know this, there is also a github app for your iphone that could make some things easier to manage.
http://mobile.github.com/
