### ISSUE TITLE
Language Export unusable - will be fixed

### ISSUE THREAD

**Issue by DanielRuf** [ACCORD5/TrellisDesk#28]
The export encodes all language data to base64 so its unreadable for humans and we cant edit the file and create a new language and import it.

The new export script will not use the base64 encoding and decoding

**Comment by djtarazona** [comment]
Base64 encoding is used to help preserve the data and avoid charset conflicts, etc.  The idea is that you will import the language pack first, then make your edits.

Pros / cons?

**Comment by DanielRuf** [comment]
BASE64 is a third bigger in size then normal data and I dont get problems with the encoding while testing?

Also the people cant know that it is base64 encoded and dont know how to decode / encode

I could use a notepad++ plugin but thing about the other ones.

I see more cons, but you could maybe set the encoding of the generated file when you export to utf8 ?

Because base64 is not so human friendly and readable

**Comment by djtarazona** [comment]
Understandable, however there are characters that will make the XML document invalid, such as < and > if used in a language string.  That was a main reason for the base64 encoding.  In regards to people not knowing, how to decode, users should not be editing the XML files directly, but rather importing them into Trellis Desk and then making edits through the ACP interface.

Suggestions on avoiding creating invalid XML documents due to reversed characters?  Maybe CDATA?

**Comment by DanielRuf** [comment]
< and > and other characters shoul be html encoded like `&gt;`
Also cdata would be also good but not base64 for exchanging and creating new languages

**Comment by djtarazona** [comment]
Yes but we can't rely on others to encode as HTML entities.  Therefore CDATA may be the better (or only) option?

**Comment by DanielRuf** [comment]
Seems to be. Much better and user friendly than base64. Also i see there no reason to use such characters like < and >
